#!/usr/bin/env bash
# This script installs nginx web server and start it listening on port 80

# Update the package manager cache
sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

sudo echo "Hello World!" > /var/www/html/index.html

sudo service nginx start
