#!/usr/bin/env bash
# This script installs nginx web server and start it listening on port 80

# Update the package manager cache
sudo apt-get update

# Upgrade the upgrade
sudo apt-get install -y upgrade

# Install nginx
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sudo service nginx stop

new_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"

sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default

# Create an error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_404_config="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_404_config/" /etc/nginx/sites-enabled/default

# test the code
sudo nginx -t

# restart the server
sudo service nginx restart
