#!/usr/bin/env bash
# A Script that generates a mysql backup and compresses it

# Create a timestamp for the backup file name
timestamp=$(date +%d-%m-%Y)

# Set the compressed archive file name
compressed_file = "$timestamp.tar.gz"

# Generate the MySQL dump of all databases
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress MySQL dump into a tar.gz achive
tar -czvf "$compressed_file" backup.sql

echo "Backup created successfully: $compressed_file"
