#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# while adding sleep 2 in between each iteration
# of the loop

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done
