#!/usr/bin/env bash
# This script run the whoami command under
# the user passed as an argument

# Check if an argument was passed
if [ $# -ne 1 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

# Run the whoami command under the specified user
sudo -u "$1" whoami
